replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: localhost:5000/brokenrobot.xyz
  pullPolicy: IfNotPresent
  tag: "latest"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
