replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

image:
  repository: localhost:5000/brokenrobot.xyz
  pullPolicy: Always
  tag: "latest"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 250m
    memory: 64M
  limits:
    cpu: 500m
    memory: 256M
